### ISSUE TITLE
Fix public interface

### ISSUE THREAD

**Issue by gryumov** [LexaLutyi/HttpClient.jl#6]
## HTTP

```julia
const Header = Pair{String,String}

to_query_decode(::Nothing) = ""
to_query_decode(x::S) where {S<:AbstractString} = x
to_query_decode(x::AbstractDict) = urlencode_query_params(x)

to_bytes(::Nothing) = Vector{UInt8}()
to_bytes(x::S) where {S<:AbstractString} = Vector{UInt8}(x)
to_bytes(x::Vector{UInt8}) = x

function request(
    method::AbstractString,
    url::AbstractString;
    headers::Vector{Header} = Header[],
    query = nothing,
    body = nothing,
    connect_timeout::Real = 60,
    read_timeout::Real = 300,
    interface::Union{String,Nothing} = nothing,
    proxy::Union{String,Nothing} = nothing,
    retries::Int64 = 1,
    status_exception::Bool = true,
    accept_encoding::String = "gzip",
    ssl_verifypeer::Bool = true,
)::Response
    req_query = to_query_decode(query)
    req_body = to_bytes(body)
    
    # ...
end
```

## WebSockets

```julia
function websocket(
    url::AbstractString;
    headers::Vector{Header} = Header[],
    query = nothing,
    connect_timeout::Real = 60,
    read_timeout::Real = 300,
    interface::Union{String,Nothing} = nothing,
    proxy::Union{String,Nothing} = nothing,
)
    # ...
end
```

**Comment by LexaLutyi** [comment]
@gryumov Я обвновил интерфейс. Некоторые аргументы не работают. Но запускать так теперь можно.

Пока не работают:
- connect_timeout
- proxy
- retries
- status_exception
- accept_encoding
- ssl_verifypeer

**Comment by gryumov** [comment]
https://github.com/LexaLutyi/HttpClient.jl/blob/main/src/web_sockets.jl#L58

не везде

**Comment by LexaLutyi** [comment]
Поправил. Но я не хочу ставить тип вектор `headers::Vector{Header}` , так как мне нравится передавать Dict

**Comment by gryumov** [comment]
HTTP заголовки могут иметь несколько значений

**Comment by LexaLutyi** [comment]
> HTTP заголовки могут иметь несколько значений, два варианта, если не нравится `Vector{Header}`
> 
> ```
> headers = {
>     'Accept-Encoding': 'gzip, deflate, br'
> }
> ```
> 
> ```
> headers = {
>     'My-Header': ['value1', 'value2']
> }
> ```
> 
> в первом случае надо иметь в виду, что тогда мы на клиента перекладываем правильный парсинг значений

Я сделал так, что можно использовать как Dict, так и Vector. Главное, чтобы это был iterable container.
Какие могут быть проблемы из-за этого? Кроме ошибки, если пользователь передаст что-то не то.

Или ты хочешь, чтобы я зафиксировал тип аргумента? Я обычно стараюсь этого избегать, чтобы у пользователя было больше свободы.

**Comment by LexaLutyi** [comment]
Ок, сделал через `Vector{Header}`. Остальное тоже поправил, где нашел.

`status_exception` теперь работает.
